BEGIN;

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE player_stats
  ADD COLUMN IF NOT EXISTS bowling_innings INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bowling_average DECIMAL(7,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS four_w_hauls INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS five_w_hauls INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dot_balls INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_metric DECIMAL(7,2) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_players_is_active ON players(is_active);

COMMIT;
